### PR TITLE
Notify varible and few things

### PR DESCRIPTION
**Pull request by icecubepiso**
Hello, i just get an idea, that we can get to all palyers customization of the Notifications.. 
IF you look at it from one side.. not everyone want to have tons of different notifications for every single resource you know.. 
The thing is, i added some Config variable like `Config.RenzuNotify` to make your notify still be there and act like before, but you can change them to your own, if you know what i mean..
I also added function in config called Notify, where you can type your notify function and it's also work at server side..

also:
• made some visual things lmao
• added manual items for ox_inventory
• added prop list what is used in client side..

### CODE REVIEW

**Review by renzuzu — CHANGES_REQUESTED** [review]
Great but
The paint items is incorrect

Its paint_red for example

**Comment by renzuzu** [comment]
And the notify function is missing? Or im blind?
( From phone)

**Comment by icecubepiso** [comment]
now i think it might be okay..

**Review by renzuzu — CHANGES_REQUESTED** [review]
typo mssg instead msg
awsome btw

**Comment by icecubepiso** [comment]
im now sure it is okay :DDD

**Pull request merged**
